<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DuCom.Core\DuCom.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="WPF-UI" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\..\Image\DuCom_256x256.ico</ApplicationIcon>
    <StartupObject>DuCom.Program</StartupObject>
    <DuComBuildDate>$([System.DateTime]::Now.ToString('yyyy-MM-dd'))</DuComBuildDate>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="BuildDate" Value="$(DuComBuildDate)" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\..\Image\DuCom_256x256.ico" Link="Assets\DuCom.ico" />
    <Resource Include="..\..\..\Image\DuCom.png" Link="Assets\DuCom.png" />
  </ItemGroup>

</Project>
