using System.IO.Ports;
using DuCom.Core.Parsing;
using DuCom.Core.Ports;
using DuCom.Core.Sending;
using DuCom.ViewModels;

namespace DuCom.Services;

internal sealed record ConfigurationSnapshot(
    int BaudRate,
    int DataBits,
    StopBits StopBits,
    Parity Parity,
    Handshake Handshake,
    string EncodingName,
    ReceiveDisplayMode ReceiveMode,
    bool TimestampEnabled,
    bool LoggingEnabled,
    string LogDirectory,
    SendMode SendMode,
    NewlinePolicy Newline,
    string TimestampFormat = "HH:mm:ss.fff",
    int LogRotationMegabytes = 40,
    bool LogRotationEnabled = true,
    int DisplayBudgetMegabytes = 64,
    bool PrivateMemoryMonitorEnabled = false,
    int PrivateMemoryThresholdMiB = 1024,
    string LogFileNameFormat = "{Port}-{yyyy}-{MM}-{dd} {HH}-{mm}-{ss}.{fff}",
    bool FreezeAfterSend = false,
    bool SendPrefixEnabled = true,
    string SendPrefix = "TX > ",
    bool PauseFollowOnMouseWheel = true,
    bool PauseFollowOnFocus = false,
    bool ShowPauseHint = true,
    bool AutoBackupEnabled = true,
    int AutoBackupPeriodDays = 7,
    bool PreventSleep = false,
    bool CloseToTaskbar = false,
    bool WordWrap = false,
    bool ShowLineNumbers = true,
    bool HighlightCurrentLine = true,
    bool ShowControlCharacters = false,
    bool ShowSpaces = false,
    bool ShowTabs = false,
    double LogFontSize = 14,
    string LogFontFamily = "Cascadia Mono",
    string Language = "",
    string ThemeMode = "Dark",
    bool ShowPortType = false,
    double SearchOpacity = 1d,
    bool IsSidebarVisible = true,
    bool IsBottomSendVisible = true,
    PortSortMode PortSortMode = PortSortMode.NameAscending,
    bool ShowHiddenPorts = false,
    bool ShowSerialPorts = true,
    bool ShowVirtualPorts = true,
    bool ShowCoverPage = true,
    bool CoverPageAnimationEnabled = true,
    int TelnetPort = 23,
    bool TelnetAllowRemote = false,
    bool TelnetAuthenticationEnabled = false,
    string? TelnetUsername = null,
    List<int>? CustomBaudRates = null,
    Dictionary<string, PortSettingSnapshot>? PortOverrides = null,
    List<string>? HiddenPorts = null,
    List<string>? CommandTargetPortNames = null,
    List<string>? RightPanePorts = null,
    SplitLayoutOrientation SplitOrientation = SplitLayoutOrientation.Vertical,
    double SplitterRatio = 0.5d,
    List<string>? SessionOrder = null,
    List<string>? OpenSessionPorts = null,
    string? SelectedSessionPort = null,
    string? SelectedRightSessionPort = null,
    bool AutoCheckUpdates = true,
    string? SkippedUpdateVersion = null,
    bool ShowMemoryMonitor = true,
    int MemoryRefreshInterval = 2,
    int SystemMemoryRefreshInterval = 5,
    int SchemaVersion = MainViewModel.CurrentSettingsSchemaVersion);

internal sealed record PortSettingSnapshot(
    int BaudRate,
    int DataBits,
    StopBits StopBits,
    Parity Parity,
    Handshake Handshake,
    string EncodingName,
    bool? DtrEnable = null,
    bool? RtsEnable = null,
    bool? DiscardNull = null,
    SendMode? SendMode = null,
    NewlinePolicy? Newline = null,
    ReceiveDisplayMode? ReceiveMode = null,
    bool? TimestampEnabled = null,
    bool? LoggingEnabled = null,
    string? LogDirectory = null,
    int? LogRotationMegabytes = null,
    bool? LogRotationEnabled = null,
    int? DisplayBudgetMegabytes = null,
    string? LogFileNameFormat = null,
    bool? SendPrefixEnabled = null,
    string? SendPrefix = null,
    bool? FollowEnd = null,
    bool? FilterEnabled = null,
    bool? AutoReconnect = null,
    Guid? HighlightRuleProjectId = null,
    bool HighlightRuleChoiceMade = false);
